name: oplibrary
author: Gad Grandez <gadgrandez@gmail.com>
homepage: https://github.com/gadgrandez/openlibrary-dart
description: A library written in dart to consume the OpenLibrary API.
version: 0.0.3

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies: